name: aspect_frontend_server
description: frontend server for flutter with AOP(aspect oriented programming)
version: 0.0.1
homepage: https://github.com/lancexin/aspect_frontend_server

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  args: ^2.3.0
  frontend_server: any
  kernel: any
  